# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
Region.create(:name => '北海道')
Region.create(:name => '東北地方')
Region.create(:name => '関東地方')
Region.create(:name => '中部地方')
Region.create(:name => '近畿地方')
Region.create(:name => '中国地方')
Region.create(:name => '四国地方')
Region.create(:name => '九州・沖縄地方')

Prefecture.create(:region_id => 1, :name => '北海道')
Prefecture.create(:region_id => 2, :name => '青森県')
Prefecture.create(:region_id => 2, :name => '岩手県')
Prefecture.create(:region_id => 2, :name => '宮城県')
Prefecture.create(:region_id => 2, :name => '秋田県')
Prefecture.create(:region_id => 2, :name => '山形県')
Prefecture.create(:region_id => 2, :name => '福島県')
Prefecture.create(:region_id => 3, :name => '茨城県')
Prefecture.create(:region_id => 3, :name => '栃木県')
Prefecture.create(:region_id => 3, :name => '群馬県')
Prefecture.create(:region_id => 3, :name => '埼玉県')
Prefecture.create(:region_id => 3, :name => '千葉県')
Prefecture.create(:region_id => 3, :name => '東京都')
Prefecture.create(:region_id => 3, :name => '神奈川県')
Prefecture.create(:region_id => 4, :name => '新潟県')
Prefecture.create(:region_id => 4, :name => '富山県')
Prefecture.create(:region_id => 4, :name => '石川県')
Prefecture.create(:region_id => 4, :name => '福井県')
Prefecture.create(:region_id => 4, :name => '山梨県')
Prefecture.create(:region_id => 4, :name => '長野県')
Prefecture.create(:region_id => 4, :name => '岐阜県')
Prefecture.create(:region_id => 4, :name => '静岡県')
Prefecture.create(:region_id => 4, :name => '愛知県')
Prefecture.create(:region_id => 5, :name => '三重県')
Prefecture.create(:region_id => 5, :name => '滋賀県')
Prefecture.create(:region_id => 5, :name => '京都府')
Prefecture.create(:region_id => 5, :name => '大阪府')
Prefecture.create(:region_id => 5, :name => '兵庫県')
Prefecture.create(:region_id => 5, :name => '奈良県')
Prefecture.create(:region_id => 5, :name => '和歌山県')
Prefecture.create(:region_id => 6, :name => '鳥取県')
Prefecture.create(:region_id => 6, :name => '島根県')
Prefecture.create(:region_id => 6, :name => '岡山県')
Prefecture.create(:region_id => 6, :name => '広島県')
Prefecture.create(:region_id => 6, :name => '山口県')
Prefecture.create(:region_id => 7, :name => '徳島県')
Prefecture.create(:region_id => 7, :name => '香川県')
Prefecture.create(:region_id => 7, :name => '愛媛県')
Prefecture.create(:region_id => 7, :name => '高知県')
Prefecture.create(:region_id => 8, :name => '福岡県')
Prefecture.create(:region_id => 8, :name => '佐賀県')
Prefecture.create(:region_id => 8, :name => '長崎県')
Prefecture.create(:region_id => 8, :name => '熊本県')
Prefecture.create(:region_id => 8, :name => '大分県')
Prefecture.create(:region_id => 8, :name => '宮崎県')
Prefecture.create(:region_id => 8, :name => '鹿児島県')
Prefecture.create(:region_id => 8, :name => '沖縄県')

Language.create(:name => 'Amazon EC2')
Language.create(:name => 'Android')
Language.create(:name => 'AngularJS')
Language.create(:name => 'Apache')
Language.create(:name => 'AWS')
Language.create(:name => 'C')
Language.create(:name => 'C#')
Language.create(:name => 'C++')
Language.create(:name => 'CakePHP')
Language.create(:name => 'CoffeeScript')
Language.create(:name => 'CSS')
Language.create(:name => 'django')
Language.create(:name => 'Docker')
Language.create(:name => 'GAS')
Language.create(:name => 'GCP')
Language.create(:name => 'git')
Language.create(:name => 'Go')
Language.create(:name => 'HTML')
Language.create(:name => 'Illustrator')
Language.create(:name => 'Java')
Language.create(:name => 'JavaScript')
Language.create(:name => 'jQuery')
Language.create(:name => 'Kotlin')
Language.create(:name => 'Laravel')
Language.create(:name => 'Linux')
Language.create(:name => 'mongodb')
Language.create(:name => 'MySQL')
Language.create(:name => 'nginx')
Language.create(:name => 'Node.js')
Language.create(:name => 'Objective-C')
Language.create(:name => 'Perl')
Language.create(:name => 'Photoshop')
Language.create(:name => 'PHP')
Language.create(:name => 'Python')
Language.create(:name => 'R')
Language.create(:name => 'React')
Language.create(:name => 'ReactNative')
Language.create(:name => 'Ruby')
Language.create(:name => 'Ruby on Rails')
Language.create(:name => 'Scala')
Language.create(:name => 'SQL')
Language.create(:name => 'Swift')
Language.create(:name => 'Symfony')
Language.create(:name => 'TypeScript')
Language.create(:name => 'Unity')
Language.create(:name => 'Vue.js')
Language.create(:name => 'WordPress')
Language.create(:name => '機械学習')
Language.create(:name => '要件定義')

Workstyle.create(:name => 'フルリモート')
Workstyle.create(:name => '一部リモート')
Workstyle.create(:name => '常駐')
